go-gorm/postgres

- postgres.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16e87b1]
goroutine 1 [running]:
gorm.io/driver/postgres.Dialector.Initialize(0xc00026d5e0, 0xc00058ec60, 0x1a6d660, 0xc00058ecc0)
/home/user/.go/pkg/mod/gorm.io/driver/postgres@v0.2.6/postgres.go:63 +0x171
gorm.io/gorm.Open(0x1d0c800, 0xc000693168, 0xc0000a8d00, 0x0, 0x270dac0, 0x7fc2b93a2e98)
/home/user/.go/pkg/mod/gorm.io/gorm@v0.2.24/gorm.go:108 +0x7d6
gitlab.com/org/app/user/internal/db/user.New(0xc000387f60, 0xc000387f60, 0x0, 0x193c860)
/home/user/ws/org/user/internal/db/user/user.go:29 +0xdb
gitlab.com/org/app/internal/handler/user.NewHandler(0xc000693160, 0x0, 0x0, 0x0)
/home/user/ws/org/user/internal/handler/user/handler.go:31 +0x11b …
```
> Fix: Initialize(): nil ptr deref with not handled err

- postgres.go
`bigint` is currently used to store Go `int32` in Postgres. `integer` should
suffice for the range, and it is the recommended default as "it offers the best
balance between range, storage size, and performance": https://www.postgresql.org/docs/10/datatype-numeric.html
Related to: https://github.com/go-gorm/gorm/pull/1536
> Fix Postgres types used to store signed integers

- migrator.go
Implement `ColumnTypes` for `postgres`.
Information for each column type is taken from the `information_schema.columns` table:
- `column_name` is the name of the column
- `is_nullable` is a (nullable) string, equal to `YES` if nullable, `NO` if `not_null`
- `udt_name` is the (short) name of the type (e.g., `varchar` for `character varying`)
- `character_maximum_length` is the (nullable) max length of character columns
- `numeric_precision` is the (nullable) precision of numeric columns
- `numeric_precision_radix` is the (nullable) radix used for precision for numeric columns, and it's equal to `10` for numeric columns, `2` for integer columns
- `numeric_scale` is the (nullable) scale of numeric columns
[This PR](https://github.com/go-gorm/playground/pull/183) runs the tests that broke …
> implement Migrator.ColumnTypes

- migrator.go
My previous PR mixed up `table_schema` and `table_catalog`. In `postgres`, the current database is stored in `table_catalog`, while in `mysql` it's stored in `table_schema`. I mixed them up while opening the two PRs.
Right now, the`ColumnTypes` implementation for `postgres` returns an empty list of columns. This PR fixes this.
The tests I were running were not covering the case where no column was found. I fixed them here: https://github.com/go-gorm/playground/pull/183
I'm sorry for the mistake.
> fix table schema and table catalog mixup

- migrator.go
- postgres.go
Precision for timestamps is stored in the `datetime_precision` column of `information_schema.columns`.
This PR takes the `datetime_precision` and returns it from the `DecimalPrecision` function.
There is also a fix for the `DataTypeOf` function: the `precision` was not taken into account when creating a new datetime column.
> retrieve timestamp precision from DB

- migrator.go
Add column comment for postgresql, reimplement the `CreateTable` `AddColumn` `MigrateColumn` methods
For example, define the model:
```golang
type Acl struct {
ID   uint64
Name string `gorm:"comment:'access control name'"`
}
```
> Add column comment for postgresql

- README.md
In DSN string, the host is missing.
> Add missing host in DSN

- README.md
Should use `dbname`, see https://pkg.go.dev/github.com/jackc/pgconn#ParseConfig
> Fix DSN dbname parameter in README

- migrator.go
Related to go-gorm/gorm#4423.
https://www.postgresql.org/docs/current/sql-createindex.html
```go
type User struct {
gorm.Model
Name string `gorm:"index:,option:CONCURRENTLY"`
}
```
```
2021/05/19 03:56:58 /go/pkg/mod/gorm.io/driver/postgres@v1.0.8/migrator.go:134
[6.462ms] [rows:0] CREATE INDEX CONCURRENTLY "idx_users_name" ON "users" ("name")
```
> Add create index concurrently option

- migrator.go
fix: calling Migrator.HasTable() when the DB is offline would cause a panic. 
the panic looked like:
```
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc40d76]
goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
/opt/hostedtoolcache/go/1.15.13/x64/src/database/sql/sql.go:3155 +0x76
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
/opt/hostedtoolcache/go/1.15.13/x64/src/database/sql/sql.go:3151 +0x33
panic(0x14645a0, 0x218ded0)
/opt/hostedtoolcache/go/1.15.13/x64/src/runtime/panic.go:969 +0x1b9
database/sql.(*Rows).Next(0x0, 0x1653226)
/opt/hostedtoolcache/go/1.15.13/x64/src/database/sql/sql.go:2835 +0x30 …
```
> fix: calling Migrator.HasTable() when the DB is offline would cause a panic

- migrator.go
This change uses the pg_type table to get the real size of numeric column types like `integer` and `bigint` so that the automigration logic functions correctly.
NOTE: this change may trigger column type changes because the previous logic wasn't detecting column type size at all for some types.
For example: in Gorm v1 `int` fields were treated as 32-bit values (`integer` in postgresql); however, in v2 they are now 64-bit values (`bigint`). Because gorm couldn't extract a type size from the type name `integer` it did not detect that a schema change was needed. With this change, these fields would be migrated from `integer` to `bigint`.
I described the issue that we were hitting in this issue in the main gorm repo: https://github.com/go-gorm/gorm/issues/4641
In brief: there are some column …
> Use the pg_type table to get valid type sizes for numeric types

- migrator.go
What did this pull request do?
fix the bug
E0311 11:04:07.442889   19254 casbin/casbin.go:62] ceshi1 pq: column "id" of relation "t_casbin_rule" already exists
User Case Description
postgressql
schema: ceshi1
table: ceshi1.t_casbin_rule
> fix postgres schema

- migrator.go
- postgres.go
for `go-staticcheck` warning
https://staticcheck.io/docs/checks#S1020
https://staticcheck.io/docs/checks#S1007
> chore: code style

- migrator.go
- postgres.go
`AlterColumn` throw error when type sercial
Do I need to create a test on gorm?
https://github.com/go-gorm/gorm/issues/5047
> fix: alter serial column

- migrator.go
- [V] Do only one thing
- [V] Non breaking API changes
- [V] Tested
Prevents migrations breaking while executing them inside a transaction.
Performing migration inside a transaction, which alters a column, doesn't work if new connection is created. Instead, always reuse old one
> Do not attempt to create a new connection in AlterColumn #103

- migrator.go
close https://github.com/go-gorm/gorm/issues/5478
> fix: handle database type array

- migrator.go
Solves issue #120 
Description on issue #120
> Fixes cockroachdb composite index name inspection

- migrator.go
https://www.postgresql.org/docs/11/storage-file-layout.html
> Caution
Note that while a table's filenode often matches its OID, this is not necessarily the case; some operations, like TRUNCATE, REINDEX, CLUSTER and some forms of ALTER TABLE, can change the filenode while preserving the OID. Avoid assuming that filenode and table OID are the same. Also, for certain system catalogs including pg_class itself, pg_class.relfilenode contains zero. The actual filenode number of these catalogs is stored in a lower-level data structure, and can be obtained using the pg_relation_filenode() function.
> fix: use oid replace relfilenode in check column type

- migrator.go
AutoMigrate fails with `sql: expected 0 arguments, got 1` when `Statement.Vars` is null
> AutoMigrate fails with `sql: expected 0 arguments, got 1` 

- go.mod
- go.sum
- migrator.go
refer to https://github.com/go-gorm/gorm/pull/5778
> fix: reset prepared stmts when table changed

- migrator.go
example:
"country" varchar(4) DEFAULT 'CN'
column.DefaultValueValue = "'CN'::character varying"
- [] Do only one thing
- [] Non breaking API changes
- [] Tested
> fix migrator default value regexp

- migrator.go
Disabling add constraint when constraint doesn't present in model but present in the database.
For example run automigrate for this Model
```
type Values struct {
Name  string `gorm:"unique"`
MyVal  bool   
}
....
db.Migrator().AutoMigrate(&Values{})
```
Try again after removing constraint "unique" from Name field
```
type Values struct {
Name  string 
MyVal  bool   
}
....
db.Migrator().AutoMigrate(&Values{})
```
Got errors messages:
```
ERROR: relation "idx_valuses_name" already exists (SQLSTATE 42P07)
```
> Disable add existing constraint

- migrator.go
Currently, CockroachDB returns `:::int8` together with their default values. We have a regex to remove it, that solves issues with PostgreSQL values, but it doesn't solve cockroachdb ones. So, I'm adding another regex to fix it.
Also, column field types has aliases, and the migrator check them to decide if we need to ALTER a column or not. But the driver is not checking it, so, I'm adding this alias check as well.
You can test this this model:
```
type Example struct {
Code   int    `gorm:"default:0"`
}
```
It would trigger the ALTER COLUMN every time since `int` returns `int8` and wasn't considering the alias to `bigint`. Also, it would have issues with the `default:0`, since it would check against `0:::int8` and `0`.
> [CockroachDB] Fixing how it handle fields DEFAULT values and column types

- migrator.go
Fix `USING ?::?` sql for boolean field on `AlterColumn` func
Without this, it will report error as I described in the issue https://github.com/go-gorm/postgres/issues/164
If we want to change column from smallint to boolean, it will report error like below:
```bash
2023/02/28 14:03:35 /home/user/go/pkg/mod/gorm.io/driver/postgres@v1.4.8/migrator.go:318 ERROR: cannot cast type smallint to boolean (SQLSTATE 42846)
[0.374ms] [rows:0] ALTER TABLE "column_structs" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean
```
We only need to fix sql become `USING xxx::int::boolean` for boolean field in func `AlterColumn` in `postgres@v1.4.8/migrator.go`
> fix : fail to alter column from smallint to boolean

- error_translator.go
Currently the translating error feature is only working for pgx driver but since Gorm is supporting both pg & pgx drivers for Postgres, this PR will add support for pg driver as well.
Here is the reported issue: https://github.com/go-gorm/gorm/issues/6299
> feat: support for traslating error for pg driver

- error_translator.go
- [Y ] Do only one thing
- [ Y] Non breaking API changes
- [ Y] Tested
Added 23503 pgerrcode support and updated the error conversion from pg error to gorm error approach
> added 23503 pgerrcode support and updated the error conversion approach

- .github/workflows/tests.yml
- error_translator.go
- error_translator_test.go
- go.mod
- go.sum
For better development the developer-friendly error ForeignKeyViolated has been implemented on the driver so it will translate all ForeignKeyViolatation errors to native gorm error ForeignKeyViolated.
Task 3 of the incomplete feature: https://github.com/go-gorm/gorm/issues/6345
> feat: foreign key violated error

- migrator.go
Adds proper work for "time stamp with time zone" type
I've faced extra "ALTER TABLE..." requests on every app start with Gorm auto-migrate. Investigated that Gorm can't recognize timestamp with timezone type because it comes as 'timestamptz' from postgres
> Add timestamp with timezone alias

- migrator.go
Fixing incorrect default value in auto generated models.
If DB column definition has `column name text default value ''` then the generated model will have the Go tag: `default:"''::text"` and value `''::text` will be written to DB column as default value.
> fix text default value produces "'::text'" as value

- migrator.go
The query only joined on constraint name and constraint schema which resulted in constraints from other tables (but same column name) returned.
> Fix query join for constraint_column_usage

- error_translator.go
- error_translator_test.go
Add support for invalid column error translation
```go
type Model struct {
Field string
}
dsn := "host=localhost port=5432 user=user password=pass dbname=db sslmode=disable TimeZone=Asia/Tehran"
db, ـ := gorm.Open(postgres.Open(dsn), &gorm.Config{TranslateError: true})
db.AutoMigrate(&Model{})
var m Model
err = db.First(&m, "wrongfield = ?", "value").Error
if errors.Is(err, gorm.ErrInvalidField) {
fmt.Println("Invalid Field")
} else if err != nil {
fmt.Println("Unknown error")
}
```
> Feature sqlstate support

- migrator.go
- migrator_test.go
Fixing incorrect default value in auto generated models.
The current version(master)  ignore default value if it contains type cast.
also will fix following PR:
https://github.com/go-gorm/postgres/pull/210
https://github.com/go-gorm/postgres/pull/201
related issues:
https://github.com/go-gorm/gorm/issues/6543
related PR:
https://github.com/go-gorm/postgres/pull/143
> fix: default value with typecast and tests

- migrator.go
- migrator_test.go
Same behavior as in other drivers. 
https://github.com/go-gorm/mysql/blob/master/migrator.go#L296
https://github.com/go-gorm/sqlite/blob/master/ddlmod.go#L146
relation to https://github.com/go-gorm/gorm/pull/6579
discussion: https://github.com/go-gorm/postgres/pull/211#discussion_r1357809828
> fix: change DefaultValueValue to the same as other drivers

- postgres.go
This PR allows the developer to take responsability of column names and table names correctness,
by correctness I mean no special characters and no postgres reserved keywords.
Benefits :
- less run time for checking each byte for an invalid character,
- more flexibility when the developer wants to ignore casing in his database columns and table names
In my case, the double quotes around table names and columns, make my query case sensitive to the casing of table names
and columns.
In my case, performance is crucial, avoiding going over bytes in the query, could be significant on the long run
> allow ignoring escape and quoting

- postgres.go
This PR addresses [issue-191](https://github.com/go-gorm/postgres/issues/191). It overrides gorm's default maximum identifier length by Postgres maximum identifier length of 63.
provide a general description of the code changes in your pull request
It sets default max identifier length to that of Postgres, which is 63, without changing anyother naming strategy, if defined by user.
> override identifier length for postgres

- postgres.go
if limit and offset use the parameter  in new gorm version，must remove config vars before bindvar to ,and then restore them.
this is necessary for  limit and offset binding parameters issue 
https://github.com/go-gorm/gorm/pull/6806
> let gorm support  limit and offset binding parameters,change the BindVar of postgres driver

- migrator.go
See https://github.com/go-gorm/gorm/issues/6381.
tested with https://github.com/go-gorm/gorm/pull/6386
> refactor: distinguish between Unique and UniqueIndex

- go.mod
- go.sum
for https://github.com/go-gorm/gorm/pull/6386
We must update gorm
Gorm must be upgraded, current [v1.5.5](https://github.com/go-gorm/postgres/releases/tag/v1.5.5) is not compatible.
It makes more sense to remove the tag.
Wait for the Gorm upgrade to complete, and then re-upgrade the postgres driver.
If we decide to do so, we can close this mr.
> update gorm to master latest

- go.mod
#247, only delete tag v1.5.5 is not enough.
If we accept this mr, we need to publish v1.5.6 to retract v1.5.5 (& v1.5.6)
> fix: retract v1.5.5

- migrator.go
> fix: dryrun migration should run select

- migrator.go
Postgres returns `udt_type` "bool" for columns of type "boolean"
Otherwise migrator detects a type mismatch and attempts to needlessly change the column type. This is normally not an issue. However, it fails when there's a view that depends on that column:
`
ALTER TABLE "records" ALTER COLUMN "deleted" TYPE boolean USING "deleted"::boolean: ERROR: cannot alter type of a column used by a view or rule (SQLSTATE 0A000)
`
This in turn fails the whole auto-migration.
> Add "boolean" as an alias for "bool"

- migrator.go
`fieldColumnType.DatabaseTypeName()` returns non capitalized string, while `fileType.SQL` returns capitalized string. This commit aims to fix this and avoid detecting a type change when the type did not change.
- [ x ] Do only one thing
- [ x ] Non breaking API changes
- [ x ] Tested
Fix same type comparing when running auto-migrate
When running auto migrate, we detected we ended up attempting to execute the statement.
```
ALTER TABLE "myTable" ALTER COLUMN "myColumn" TYPE JSONB USING "myColumn"::JSONB
```
This resulted in an error since our database (CockroachDB) does not allow type alter statements on JSONB columns.
After reviewing the code and debugging, I noticed that this behaviour was due to this comparison.  
`fieldColumnType.DatabaseTypeName()` returns non capitalised string, …
> Fix same type comparing

- error_translator.go
- error_translator_test.go
- go.mod
- go.sum
Added 23514 pgerrcode support
Detailed here: https://github.com/go-gorm/gorm/pull/6992
> Add new error for "Violation Check Constraint"

- migrator.go
A bunch of Postgres-type aliases are missing in the migrator. AutoMigrate performs an `ALTER COLUMN` even though the column already has the specified data type.
This PR adds the missing aliases, ensuring that the migrator doesn't execute the `ALTER COLUMN` statement, when the given column is already migrated.
The complete list of aliases is in Table 8.1 in the Postgres documentation [here](https://www.postgresql.org/docs/current/datatype.html).
Adding these aliases ensures that ALTER COLUMN isn't performed when invoking AutoMigrate on a table, where the columns used one of the following types:
* integer
* smallserial
* serial
* bigserial
* bit varying
* character
* character varying
* real
* double precision
* time with time zone
> Add missing postgres type aliases

- migrator.go
Check index exists after create index. If not exists, return the err.
We run into this case, because we use the same index name for difference table, and the migration executed successfuly. But when  use do some request, we got a err  `ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10` becase we must make sure the index exists.
> fix: create index failed without err

- migrator.go
* issue : #289 
There is a default value in the existing column property, but if the column property to be changed does not have a default value, no processing is performed. Need to cover this case.
> [#289] Add coverage for eliminating default value tag

- migrator.go
- [X ] Do only one thing
- [ X] Non breaking API changes
- [ X] Tested
When creating indexes, the option argument is taken into account.
When creating indexes, users might need greater control over the resulting DDL statement. For example, users need a way to specify "NULLS [ NOT ] DISTINCT" SQL option when working with Postgres as described here:  https://www.postgresql.org/docs/current/sql-createindex.html
Despite documentation stating that `option` param is supported: https://gorm.io/docs/indexes.html, Postgres Mirgator implementation does not use it. Example of use opened issue that will be closed by this PR: https://github.com/go-gorm/gorm/issues/6085
> Respect index option param.

- migrator.go
This resolves issue #293.  The issue was a prior PR to allow for other options blindly applied the options at the end of the SQL statement.  However, `concurrently` does not go at the end of the SQL statement.  Thus #288 broke the usage of concurrently.  Used the playground pointing to this change to verify that the fix works without breaking the issue "fixed" in #288.  
The playground verification https://github.com/go-gorm/playground/pull/779.
My case is simple.  I want to create an index concurrently as the documents state.  The documents clearly state that concurrently is an OPTION.  https://gorm.io/docs/indexes.html.
> fix concurrent index creation

- postgres.go
- postgres_test.go
Add handling for string length's that exceed 10485760 so that PostgreSQL won't complain about the field length.
Add tests to confirm change.
Enable PostgreSQL to store text fields that exceed 10485760 in length, which is the maximum length of a varchar as per https://www.postgresql.org/docs/current/datatype-character.html.
This is similar to MySQL and SQLServer where specific lengths trigger a difference in the used data type.
> Add varchar limit detection as per PostgreSQL limits

- migrator.go
> Optimize regular expression compilation cache

- postgres.go
This PR enables users to supply custom stdlib.OptionOpenDB to the underlying Postgres driver.
We're using an Azure Postgres instance that requires access token authentication. Since these tokens expire periodically, we need the ability to pass a `BeforeConnect` hook to `jackc/pgx`. This allows us to detect expired tokens and fetch new ones automatically before establishing a connection.
> Allow users to pass in their own stdlib.OptionOpenDB
